/**
 * Per-hero ability-slot table for sound-mod classification.
 *
 * Maps each Deadlock sound-path codename (see heroSoundCodenames.ts) to its 4
 * ability slots (slot 4 = ultimate). Generated from docs/per-ability-sound-map.json
 * (built from the base game pak + deadlock-api, validated against real mods at
 * 97% file-level accuracy). `token` is the ability's internal name, `display` the
 * localized name, `image` the deadlock-api icon URL. The classifier in
 * abilitySounds.ts resolves a sound file to a slot via: aN path token > display/
 * token match > curated override.
 *
 * Regenerate (do not hand-edit): docs/per-ability-sound-map.json is the source.
 */

import type { AbilitySlot, AbilitySlotMeta } from '../../../src/types/mod';

export const HERO_ABILITY_SLOTS: Readonly<
    Record<string, Readonly<Partial<Record<AbilitySlot, AbilitySlotMeta>>>>
> = {
    abrams: { 1: { token: 'heal', display: 'Siphon Life', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bull_drain.png' }, 2: { token: 'charge', display: 'Shoulder Charge', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bull_charge.png' }, 3: { token: 'beefy', display: 'Infernal Resilience', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bull_beef.png' }, 4: { token: 'leap', display: 'Seismic Impact', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bull_jump.png' } },
    astro: { 1: { token: 'barrel', display: 'Powder Keg', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/astro/holliday_powder_keg.png' }, 2: { token: 'pad', display: 'Bounce Pad', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/astro/holliday_bounce_pad.png' }, 3: { token: 'crackshot', display: 'Crackshot', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/astro/holliday_crackshot.png' }, 4: { token: 'lasso', display: 'Spirit Lasso', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/astro/holliday_spirit_lasso.png' } },
    bebop: { 1: { token: 'uppercut', display: 'Exploding Uppercut', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bebop/bebop_uppercut.png' }, 2: { token: 'bomb', display: 'Sticky Bomb', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bebop/bebop_sticky_bomb.png' }, 3: { token: 'hook', display: 'Grapple Arm', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bebop/bebop_hook.png' }, 4: { token: 'laser_beam', display: 'Hyper Beam', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bebop/bebop_hyper_beam.png' } },
    bookworm: { 1: { token: 'dragonfire', display: 'Bookwyrm', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bookworm/bookworm_dragon.png' }, 2: { token: 'knightbarrier', display: 'Plot Armor', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bookworm/bookworm_defendandfight.png' }, 3: { token: 'aoemagic', display: 'Captivating Read', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bookworm/bookworm_blindinglight.png' }, 4: { token: 'knightcharge', display: 'Rallying Charge', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bookworm/bookworm_charge.png' } },
    cadence: { 1: { token: 'ability_anthem', display: 'cadence_ability_anthem', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/cadence/cadence_ability_1.png' }, 2: { token: 'ability_silencecontraptions', display: 'cadence_ability_silencecontraptions', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/cadence/cadence_ability_2.png' }, 3: { token: 'ability_lullaby', display: 'cadence_ability_lullaby', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/cadence/cadence_ability_3.png' }, 4: { token: 'ability_crescendo', display: 'cadence_ability_crescendo', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/cadence/cadence_ability_4.png' } },
    chrono: { 1: { token: 'pulse_grenade', display: 'Pulse Grenade', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/chrono/chrono_time_bomb.png' }, 2: { token: 'time_wall', display: 'Time Wall', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/chrono/chrono_time_wall.png' }, 3: { token: 'kinetic_carbine', display: 'Kinetic Carbine', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/duo/duo_attack.png' }, 4: { token: 'swap', display: 'Paradoxical Swap', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/chrono/chrono_swap.png' } },
    doorman: { 1: { token: 'bomb', display: 'Call Bell', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/doorman/doorman_bell.png' }, 2: { token: 'doorway', display: 'Doorway', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/doorman/doorman_doorway.png' }, 3: { token: 'luggage_cart', display: 'Luggage Cart', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/doorman/doorman_luggagetrolley.png' }, 4: { token: 'hotel', display: 'Hotel Guest', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/doorman/doorman_elevator.png' } },
    drifter: { 1: { token: 'blood_blast', display: 'Rend', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/drifter/drifter_claw.png' }, 2: { token: 'shadow_mark', display: 'Stalker\'s Mark', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/drifter/drifter_stalkersmark.png' }, 3: { token: 'hunger', display: 'Bloodscent', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/drifter/drifter_thehunger.png' }, 4: { token: 'darkness', display: 'Eternal Night', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/drifter/darkness.png' } },
    dynamo: { 1: { token: 'stomp', display: 'Kinetic Pulse', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/sumo/sumo_stomp.png' }, 2: { token: 'sphere', display: 'Quantum Entanglement', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/sumo/sumo_quantum.png' }, 3: { token: 'nikuman', display: 'Rejuvenating Aurora', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/sumo/sumo_pork_bun.png' }, 4: { token: 'vacuum', display: 'Singularity', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/sumo/sumo_vacuum.png' } },
    familiar: { 1: { token: 'ability02', display: 'Pillow Toss', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/familiar/familiar_pillow.png' }, 2: { token: 'attach', display: 'Tag Along', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/familiar/familiar_tag_along.png' }, 3: { token: 'helpinghands', display: 'Lil Helpers', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/familiar/familiar_helpers.png' }, 4: { token: 'ability01', display: 'Naptime', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/familiar/familiar_sleep.png' } },
    fathom: { 1: { token: 'scalding_spray', display: '', image: null }, 2: { token: 'breach', display: '', image: null }, 3: { token: 'reefdweller_harpoon', display: '', image: null }, 4: { token: 'lurkers_ambush', display: '', image: null } },
    fencer: { 1: { token: 'throwblade', display: 'Disengaging Sigil', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/fencer/fencer_sigil.png' }, 2: { token: 'riposte', display: 'Riposte', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/fencer/fencer_riposte.png' }, 3: { token: 'lunge', display: 'Flawless Advance', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/fencer/fencer_lungingstab.png' }, 4: { token: 'ultimate', display: 'Itani Lo Sahn', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/fencer/fencer_ult.png' } },
    forge: { 1: { token: 'shieldedsentry', display: 'Mini Turret', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/engineer_turret.png' }, 2: { token: 'resupply', display: 'Medicinal Specter', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/engineer_resupply.png' }, 3: { token: 'wall', display: 'Spectral Wall', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/engineer_fissure_2.png' }, 4: { token: 'barrage', display: 'Heavy Barrage', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/engineer_rockets.png' } },
    frank: { 1: { token: 'shocktarget2', display: 'Pain Battery', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/frank/frank_pain_battery.png' }, 2: { token: 'selfzap', display: 'Jumpstart', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/frank/frank_jump_start.png' }, 3: { token: 'painaura', display: 'Aura of Suffering', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/frank/frank_aura_of_suffering.png' }, 4: { token: 'revive', display: 'Shocking Reanimation', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/frank/frank_shocking_reanimation.png' } },
    ghost: { 1: { token: 'bomb', display: 'Essence Bomb', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/spectre/blood_bomb.png' }, 2: { token: 'drain', display: 'Life Drain', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/spectre/life_drain.png' }, 3: { token: 'shards', display: 'Malice', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/spectre/geist_dagger.png' }, 4: { token: 'swap', display: 'Soul Exchange', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/spectre/blood_exchange.png' } },
    gigawatt: { 1: { token: 'ball', display: 'Lightning Ball', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/giga_ball.png' }, 2: { token: 'charge', display: 'Static Charge', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/giga_static.png' }, 3: { token: 'surge', display: 'Power Surge', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/giga_chain.png' }, 4: { token: 'cloud', display: 'Storm Cloud', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/giga_storm.png' } },
    haze: { 1: { token: 'dagger', display: 'Sleep Dagger', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/haze/haze_sleep_dagger.png' }, 2: { token: 'bomb', display: 'Smoke Bomb', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/haze/haze_smoke_bomb.png' }, 3: { token: 'damage', display: 'Fixation', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/haze/haze_fixation.png' }, 4: { token: 'flurry', display: 'Bullet Dance', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/haze/haze_bullet_flurry.png' } },
    hornet: { 1: { token: 'chain', display: 'Stake', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/hornet/vindicta_stake.png' }, 2: { token: 'leap', display: 'Flight', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/hornet/vindicta_flight.png' }, 3: { token: 'sting', display: 'Crow Familiar', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/hornet/hornet_crow.png' }, 4: { token: 'snipe', display: 'Assassinate', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/hornet/hornet_assassinate.png' } },
    inferno: { 1: { token: 'projectile', display: 'Napalm', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/inferno_molotov.png' }, 2: { token: 'dash', display: 'Flame Dash', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/inferno_dash.png' }, 3: { token: 'afterburn', display: 'Afterburn', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/inferno_deflect.png' }, 4: { token: 'bomb', display: 'Concussive Combustion', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/inferno_bomb.png' } },
    kali: { 1: { token: 'spinning_blade', display: 'citadel_ability_kali_spinning_blade', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/kali/kali_oscilloblade.png' }, 2: { token: 'disruptive_charge', display: 'citadel_ability_kali_disruptive_charge', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/kali/kali_speed_burst.png' }, 3: { token: 'dust_storm', display: 'ability_kali_dust_storm', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/kali/kali_whirling_blade.png' }, 4: { token: 'trappers_bolo', display: 'ability_kali_trappers_bolo', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/bebop/bebop_sticky_bomb.png' } },
    kelvin: { 1: { token: 'grenade', display: 'Frost Grenade', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/kelvin/freezing_grenade.png' }, 2: { token: 'icepath', display: 'Ice Path', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/kelvin/ice_path.png' }, 3: { token: 'icebeam', display: 'Arctic Beam', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/kelvin/ice_beam.png' }, 4: { token: 'dome', display: 'Frozen Shelter', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/kelvin/frozen_shelter.png' } },
    lash: { 1: { token: 'down_strike', display: 'Ground Strike', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/lash/lash_death_slam.png' }, 2: { token: 'lash', display: 'Grapple', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/lash/lash_lash.png' }, 3: { token: 'flog', display: 'Flog', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/lash/lash_flog.png' }, 4: { token: 'ultimate', display: 'Death Slam', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/lash/lash_counter_lash.png' } },
    magician: { 1: { token: 'magicbolt', display: 'Vexing Bolt', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/magician/magician_magicbolt.png' }, 2: { token: 'cloneturret', display: 'Spectral Assistant', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/magician/magician_cloneturret.png' }, 3: { token: 'animalhexarea', display: 'Rabbit Hex', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/magician/magician_animalcurse.png' }, 4: { token: 'copyult', display: 'Audience Participation', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/magician/magician_copyult.png' } },
    mirage: { 1: { token: 'fire_beetles', display: 'Fire Scarabs', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/mirage/mirage_fire_beetles.png' }, 2: { token: 'tornado', display: 'Dust Devil', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/mirage/mirage_tornado.png' }, 3: { token: 'sand_phantom', display: 'Djinn\'s Mark', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/mirage/mirage_sand_phantom.png' }, 4: { token: 'teleport', display: 'Traveler', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/mirage/mirage_teleport.png' } },
    mokrill: { 1: { token: 'intimidate', display: 'Scorn', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/grappler/grappler_regen.png' }, 2: { token: 'burrow', display: 'Burrow', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/grappler/grappler_spin.png' }, 3: { token: 'sand', display: 'Sand Blast', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/grappler/grappler_throw_sand.png' }, 4: { token: 'combo', display: 'Combo', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/grappler/grappler_combo.png' } },
    nano: { 1: { token: 'clustergrenade', display: 'Gloom Bombs', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/nano/nano_clustergrenade.png' }, 2: { token: 'dash', display: 'Leaping Slash', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/nano/nano_dash.png' }, 3: { token: 'catform', display: 'Ava', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/nano/nano_catform.png' }, 4: { token: 'shadow_pulse', display: 'Return to Shadows', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/nano/nano_shadow_pulse.png' } },
    necro: { 1: { token: 'hauntingskull', display: 'Jar of Dead', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/necro/necro_skull.png' }, 2: { token: 'zombiewall', display: 'Grasping Hands', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/necro/necro_hands.png' }, 3: { token: 'fear', display: 'Essence Theft', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/necro/necro_siphon.png' }, 4: { token: 'gravestone', display: 'Borrowed Decree', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/necro/necro_gravestone.png' } },
    operative: { 1: { token: 'blindside', display: 'Blindside', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/operative/operative_blindside.png' }, 2: { token: 'umbrella_maneuver', display: 'Umbrella Maneuver', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/upgrades/mods_utility/springy_boots.png' }, 3: { token: 'rapidfire', display: 'Full Auto', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/wraith_aura.png' }, 4: { token: 'revelation', display: 'Revelation', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/sumo/sumo_pork_bun.png' } },
    orion: { 1: { token: 'shot', display: 'Charged Shot', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/archer/archer_charged_shot.png' }, 2: { token: 'jump', display: 'Rain of Arrows', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/archer/archer_power_jump.png' }, 3: { token: 'trap', display: 'Spirit Snare', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/archer/imobolize_trap.png' }, 4: { token: 'arrow', display: 'Guided Owl', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/archer/archer_guided_arrow.png' } },
    priest: { 1: { token: 'flashbang', display: 'Consecrating Grenade', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/priest/priest_grenade.png' }, 2: { token: 'knockback', display: 'Gutshot', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/priest/priest_shotgun.png' }, 3: { token: 'beartrap', display: 'Hex-Lined Snap Trap', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/priest/priest_trap.png' }, 4: { token: 'weaponswap', display: 'Ira Domini', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/priest/priest_crossbow.png' } },
    punkgoat: { 1: { token: 'ult', display: 'Bashdown', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/punkgoat/goat_sigilslam.png' }, 2: { token: 'goatflip', display: 'Rising Ram', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/punkgoat/goat_risingram.png' }, 3: { token: 'blasted', display: 'Blasted', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/punkgoat/goat_blasted.png' }, 4: { token: 'tether', display: 'Chain Gang', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/punkgoat/goat_chaingang.png' } },
    shiv: { 1: { token: 'dagger', display: 'Serrated Knives', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/shiv/shiv_toss.png' }, 2: { token: 'dash', display: 'Slice and Dice', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/shiv/shiv_flash.png' }, 3: { token: 'defer_damage', display: 'Bloodletting', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/shiv/shiv_bloodletting.png' }, 4: { token: 'killing_blow', display: 'Killing Blow', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/shiv/shiv_killing_blow.png' } },
    synth: { 1: { token: 'barrage', display: 'Barrage', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/synth/synth_barrage.png' }, 2: { token: 'plasma_flux', display: 'Flying Cloak', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/synth/synth_plasma_flux.png' }, 3: { token: 'pulse', display: 'Enchanter\'s Satchel', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/synth/synth_pulse.png' }, 4: { token: 'affliction', display: 'Affliction', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/synth/synth_affliction.png' } },
    tengu: { 1: { token: 'urn', display: 'Entangling Thorns', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/tengu/tengu_storm_flask.png' }, 2: { token: 'tangotether', display: 'Kudzu Connection', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/tengu/tengu_tether.png' }, 3: { token: 'stone_form', display: 'Stone Form', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/tengu/tengu_stone_form.png' }, 4: { token: 'airlift', display: 'Air Drop', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/tengu/tengu_lightning_crash.png' } },
    tokamak: { 1: { token: 'hot_shot', display: 'tokamak_hot_shot', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/tokamak/tokamak_hot_shot.png' }, 2: { token: 'dying_star', display: 'tokamak_dying_star', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/tokamak/tokamak_dying_star.png' }, 3: { token: 'radiance', display: 'tokamak_radiance', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/tokamak/tokamak_blinding_radiance.png' }, 4: { token: 'crimson_cannon', display: 'tokamak_crimson_cannon', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/tokamak/tokamak_crimson_cannon.png' } },
    trapper: { 1: { token: 'poisonjar', display: 'Bottled Phantasmicide', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/trapper/trapper_poison_jar.png' }, 2: { token: 'webwall', display: 'Silktrap', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/trapper/trapper_web_wall.png' }, 3: { token: 'spidershield', display: 'Pest Barrier', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/trapper/trapper_spider_shield.png' }, 4: { token: 'spiderwave', display: 'Crawling Plague', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/trapper/trapper_spider_wave.png' } },
    unicorn: { 1: { token: 'radiantblast', display: 'Light Eater', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/unicorn/unicorn_flare.png' }, 2: { token: 'prismaticguard', display: 'Dazzling Trick', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/unicorn/unicorn_shield.png' }, 3: { token: 'luminousstrike', display: 'Radiant Daggers', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/unicorn/unicorn_luminousflux.png' }, 4: { token: 'dazzlingorb', display: 'Shining Wonder', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/unicorn/unicorn_orb.png' } },
    vampirebat: { 1: { token: 'steallife', display: 'Rake', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/vampirebat/vampirebat_rake.png' }, 2: { token: 'batblink', display: 'Sanguine Retreat', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/vampirebat/vampirebat_sanguine_retreat.png' }, 3: { token: 'lovebites', display: 'Love Bites', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/vampirebat/vampirebat_love_bites.png' }, 4: { token: 'batswarm', display: 'Nox Nostra', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/vampirebat/vampirebat_nox_nostra.png' } },
    viper: { 1: { token: 'debuffdagger', display: 'Screwjab Dagger', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/viper/viper_debuffdagger.png' }, 2: { token: 'venom', display: 'Lethal Venom', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/viper/viper_venom.png' }, 3: { token: 'snakedash', display: 'Slither', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/viper/viper_snakedash.png' }, 4: { token: 'petrifybola', display: 'Petrifying Bola', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/viper/viper_petrifybola.png' } },
    viscous: { 1: { token: 'goo_grenade', display: 'Splatter', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/viscous/viscous_goo_ball.png' }, 2: { token: 'restorative_goo', display: 'The Cube', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/viscous/viscous_restorative_goo.png' }, 3: { token: 'telepunch', display: 'Puddle Punch', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/viscous/viscous_goo_punch.png' }, 4: { token: 'goo_bowling_ball', display: 'Goo Ball', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/viscous/viscous_goo_sphere.png' } },
    warden: { 1: { token: 'crowd_control', display: 'Alchemical Flask', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/warden/warden_crowd_control.png' }, 2: { token: 'high_alert', display: 'Willpower', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/warden/warden_high_alert.png' }, 3: { token: 'lock_down', display: 'Binding Word', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/warden/warden_lock_down.png' }, 4: { token: 'riot_protocol', display: 'Last Stand', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/warden/warden_riot_protocol.png' } },
    werewolf: { 1: { token: 'unloadgun', display: 'Slam Fire', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/werewolf/werewolf_slamfire.png' }, 2: { token: 'kickflip', display: 'Boot Kick', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/werewolf/werewolf_jumpback.png' }, 3: { token: 'netshot', display: 'Entangling Bola', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/werewolf/werewolf_bola.png' }, 4: { token: 'transformation', display: 'Lycan Curse', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/werewolf/werewolf_lycancurse.png' } },
    wraith: { 1: { token: 'toss', display: 'Card Trick', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/wraith_card_trick.png' }, 2: { token: 'projectmind', display: 'Project Mind', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/wraith_teleport.png' }, 3: { token: 'rapidfire', display: 'Full Auto', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/wraith_aura.png' }, 4: { token: 'lift', display: 'Telekinesis', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/wraith_lift.png' } },
    wrecker: { 1: { token: 'bouldergrenade', display: 'Wrecking Ball', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/wrecker/wrecking_ball.png' }, 2: { token: 'salvage', display: 'Consume', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/wrecker/salvage.png' }, 3: { token: 'blast', display: 'Bio Blast', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/wrecker/scrap_blast.png' }, 4: { token: 'garbage_suck', display: 'Overload', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/mirage/mirage_sunfire_cataclysm.png' } },
    yamato: { 1: { token: 'slash', display: 'Power Slash', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/yamato/yamato_power_slash.png' }, 2: { token: 'strike', display: 'Flying Slash', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/yamato/yamato_flying_strike.png' }, 3: { token: 'slash', display: 'Crimson Slash', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/yamato/yamato_crimson_slash.png' }, 4: { token: 'slash', display: 'Shadow Transformation', image: 'https://assets-bucket.deadlock-api.com/assets-api-res/images/abilities/yamato/yamato_blinding_steel.png' } },
};

/**
 * Legacy sound-dir codenames that still ship files; merge into the current
 * codename before lookup (e.g. Grey Talon files under both `orion` and `archer`).
 */
export const LEGACY_SOUND_CODENAME_MERGE: Readonly<Record<string, string>> = {
    archer: 'orion',
    geist: 'ghost',
    pocket: 'synth',
};

/**
 * Hand-curated dev-token -> slot for renamed/ambiguous tokens the deadlock-api
 * name does not match (see docs/per-ability-sound-map.md). slot 4 = ultimate.
 */
export const SLOT_TOKEN_CURATION: Readonly<
    Record<string, Readonly<Record<string, AbilitySlot>>>
> = {
    magician: { animalcurse: 3 },
    nano: { ava: 3 },
    warden: { lockdown: 3 },
    wraith: { psychic: 2, psychicpulse: 2, royalflush: 1 },
};
