import { promises as fs, existsSync } from 'fs';
import { join } from 'path';
import { spawn } from 'child_process';
import { randomUUID, createHash } from 'crypto';
import { app } from 'electron';
import { getAddonsPath } from './deadlock';
import { scanMods, disableMod, enableMod, findNextAvailablePriority, type Mod } from './mods';
import { getModMetadata, setModMetadata, removeModMetadata } from './metadata';
import { encodeShareCode } from './portableProfile';
import {
    PORTABLE_PROFILE_FORMAT,
    PORTABLE_PROFILE_SCHEMA_VERSION,
    type PortableProfile,
    type PortableModEntry,
} from '../../../src/types/portableProfile';
import type { MergedModInfo, MergedModSource, UnmergeModResult } from '../../../src/types/mod';

const DEADLOCK_STEAM_APP_ID = 1422450;
const DEADLOCK_GAMEBANANA_GAME_ID = 20948;

type SupportedPlatform = 'linux-x64' | 'darwin-arm64' | 'win32-x64';

const VPKMERGE_BINARY_BY_PLATFORM: Record<SupportedPlatform, string> = {
    'linux-x64':    'vpkmerge-linux-x86_64',
    'darwin-arm64': 'vpkmerge-macos-aarch64',
    'win32-x64':    'vpkmerge-windows-x86_64.exe',
};

/**
 * Resolve the bundled vpkmerge binary path. In dev the binary lives under
 * the repo's resources/; in a packaged build electron-builder's
 * extraResources places it at process.resourcesPath/vpkmerge/.
 */
function vpkmergeBinaryPath(): string {
    const key = `${process.platform}-${process.arch}` as SupportedPlatform;
    const assetName = VPKMERGE_BINARY_BY_PLATFORM[key];
    if (!assetName) {
        throw new Error(
            `Mod merging is not available on ${process.platform}-${process.arch}. Supported: linux x64, macOS arm64, Windows x64.`
        );
    }
    const baseDir = app.isPackaged
        ? join(process.resourcesPath, 'vpkmerge')
        : join(app.getAppPath(), 'resources', 'vpkmerge');
    const full = join(baseDir, assetName);
    if (!existsSync(full)) {
        throw new Error(
            `vpkmerge binary missing at ${full}. Run \`pnpm install\` (or \`pnpm fetch-vpkmerge\`) to fetch it.`
        );
    }
    return full;
}

function runVpkmerge(args: string[], timeoutMs = 300000): Promise<void> {
    return new Promise((resolve, reject) => {
        const bin = vpkmergeBinaryPath();
        const proc = spawn(bin, args, { stdio: ['ignore', 'pipe', 'pipe'] });
        let stderr = '';
        let stdout = '';
        let killed = false;

        const timeoutId = setTimeout(() => {
            killed = true;
            proc.kill('SIGTERM');
            setTimeout(() => {
                if (!proc.killed) proc.kill('SIGKILL');
            }, 5000);
            reject(new Error(`vpkmerge timed out after ${timeoutMs / 1000} seconds`));
        }, timeoutMs);

        proc.stdout?.on('data', (d) => { stdout += d.toString(); });
        proc.stderr?.on('data', (d) => { stderr += d.toString(); });
        proc.on('close', (code) => {
            clearTimeout(timeoutId);
            if (killed) return;
            if (code === 0) {
                resolve();
            } else {
                reject(new Error(`vpkmerge exited with code ${code}: ${stderr || stdout || '(no output)'}`));
            }
        });
        proc.on('error', (err) => {
            clearTimeout(timeoutId);
            if (killed) return;
            reject(new Error(`Failed to spawn vpkmerge: ${err.message}`));
        });
    });
}

async function hashFile(path: string): Promise<string> {
    const hash = createHash('sha256');
    hash.update(await fs.readFile(path));
    return hash.digest('hex');
}

export interface MergeOptions {
    name: string;
    /** PNG/JPEG data URL for the collage thumbnail. Generated by the renderer
     *  from the source mod thumbnails. */
    thumbnailDataUrl?: string;
    /** Pass --strict to vpkmerge so any file-path collision aborts the merge
     *  instead of silently letting later inputs win. Off by default to match
     *  Deadlock's runtime "higher pakNN loads later, last write wins" model. */
    strict?: boolean;
}

export interface MergeResult {
    mod: Mod;
    disabledSources: Mod[];
}

export async function mergeMods(
    deadlockPath: string,
    modIds: string[],
    options: MergeOptions
): Promise<MergeResult> {
    const trimmedName = options.name.trim();
    if (!trimmedName) throw new Error('A name is required for the merged mod.');
    if (modIds.length < 2) throw new Error('Select at least two mods to merge.');

    const installed = await scanMods(deadlockPath);
    const sources: Mod[] = [];
    for (const id of modIds) {
        const found = installed.find((m) => m.id === id);
        if (!found) throw new Error(`Selected mod not found (id: ${id}).`);
        const meta = getModMetadata(found.fileName);
        if (meta?.merged) {
            throw new Error(
                `"${meta.modName || found.name}" is already a merged mod. Unmerge it first.`
            );
        }
        sources.push(found);
    }

    // Sort by priority ascending so the highest-priority source is last in
    // the vpkmerge argv. vpkmerge's last-input-wins matches Deadlock's
    // higher-pakNN-loads-later override semantics.
    sources.sort((a, b) => a.priority - b.priority);

    const portable = buildPortableForSources(sources, trimmedName);
    const shareCode = encodeShareCode(JSON.stringify(portable));

    const priority = await findNextAvailablePriority(deadlockPath);
    const priorityStr = String(priority).padStart(2, '0');
    const mergedFileName = `pak${priorityStr}_dir.vpk`;
    const addonsPath = getAddonsPath(deadlockPath);
    const mergedPath = join(addonsPath, mergedFileName);

    if (existsSync(mergedPath)) {
        throw new Error(`Cannot create merged mod: ${mergedFileName} already exists.`);
    }

    const args: string[] = [];
    if (options.strict) args.push('--strict');
    args.push(mergedPath);
    for (const src of sources) args.push(src.path);

    try {
        await runVpkmerge(args);
    } catch (err) {
        try { await fs.unlink(mergedPath); } catch { /* ignore partial-output cleanup */ }
        throw err;
    }

    const preDisableSnapshot: MergedModSource[] = sources.map((src) => {
        const meta = getModMetadata(src.fileName);
        return {
            fileName: src.fileName,
            modName: meta?.modName || src.name,
            thumbnailUrl: meta?.thumbnailUrl,
            gameBananaId: meta?.gameBananaId,
            gameBananaFileId: meta?.gameBananaFileId,
            enabledAtMergeTime: src.enabled,
            priorityAtMergeTime: src.priority,
        };
    });

    // Disable each enabled source so its priority slot frees up and the
    // engine stops loading the original. disableMod returns the post-move
    // Mod so we can record the actual on-disk filename (it may have been
    // renamed by reconcileEnabledDisabledCollisions).
    const disabledSources: Mod[] = [];
    for (let i = 0; i < sources.length; i++) {
        const src = sources[i];
        if (src.enabled) {
            const after = await disableMod(deadlockPath, src.id);
            disabledSources.push(after);
            preDisableSnapshot[i].fileName = after.fileName;
        } else {
            disabledSources.push(src);
        }
    }

    const merged: MergedModInfo = {
        id: randomUUID(),
        createdAt: new Date().toISOString(),
        shareCode,
        sources: preDisableSnapshot,
    };

    const sha256 = await hashFile(mergedPath);
    // Scrub any orphan metadata at this slot before writing so we don't
    // inherit fields from a prior occupant.
    removeModMetadata(mergedFileName);
    setModMetadata(mergedFileName, {
        modName: trimmedName,
        thumbnailUrl: options.thumbnailDataUrl,
        sha256,
        merged,
    });

    const finalMods = await scanMods(deadlockPath);
    const newMod = finalMods.find((m) => m.fileName === mergedFileName);
    if (!newMod) {
        throw new Error('Merged mod was created on disk but could not be located in the rescan.');
    }
    return { mod: newMod, disabledSources };
}

function buildPortableForSources(sources: Mod[], profileName: string): PortableProfile {
    const mods: PortableModEntry[] = [];
    for (const src of sources) {
        const meta = getModMetadata(src.fileName);
        const gbId = meta?.gameBananaId ?? src.gameBananaId;
        const fileId = meta?.gameBananaFileId ?? src.gameBananaFileId;
        if (!gbId || !fileId) continue; // local mod — fast-path unmerge still works
        mods.push({
            source: 'gamebanana',
            ref: {
                submissionId: gbId,
                fileId,
                section: meta?.sourceSection || 'Mod',
            },
            enabled: true,
            priority: src.priority,
            hint: {
                name: meta?.modName || src.name,
                category: meta?.categoryName,
                fileLabel: meta?.variantLabel || meta?.fileDescription || meta?.sourceFileName,
                originalFileName: meta?.sourceFileName,
                thumbnailUrl: meta?.thumbnailUrl,
                nsfw: meta?.nsfw,
                isArchived: meta?.isArchived,
            },
        });
    }
    return {
        format: PORTABLE_PROFILE_FORMAT,
        schemaVersion: PORTABLE_PROFILE_SCHEMA_VERSION,
        game: {
            steamAppId: DEADLOCK_STEAM_APP_ID,
            gameBananaGameId: DEADLOCK_GAMEBANANA_GAME_ID,
            name: 'Deadlock',
        },
        exportedAt: new Date().toISOString(),
        exportedBy: { tool: 'grimoire', version: app.getVersion() },
        profile: { name: profileName },
        mods,
    };
}

/**
 * Reverse a merge: re-enable the source VPKs (if they're still on disk) and
 * delete the merged VPK. Sources that are missing are reported via
 * missingSourceFileNames so the caller can offer the share code via the
 * existing portable-profile import flow.
 */
export async function unmergeMod(
    deadlockPath: string,
    mergedModId: string
): Promise<UnmergeModResult> {
    const installed = await scanMods(deadlockPath);
    const target = installed.find((m) => m.id === mergedModId);
    if (!target) throw new Error(`Merged mod not found (id: ${mergedModId}).`);

    const meta = getModMetadata(target.fileName);
    if (!meta?.merged) {
        throw new Error(`"${meta?.modName || target.name}" is not a merged mod.`);
    }
    const manifest = meta.merged;

    const recovered: Mod[] = [];
    const missingSourceFileNames: string[] = [];

    for (const src of manifest.sources) {
        // Rescan each iteration so disableMod-induced renames in earlier
        // iterations are reflected in the id lookup.
        const currentMods = await scanMods(deadlockPath);
        const onDisk = currentMods.find((m) => m.fileName === src.fileName);
        if (!onDisk) {
            missingSourceFileNames.push(src.fileName);
            continue;
        }
        if (src.enabledAtMergeTime && !onDisk.enabled) {
            recovered.push(await enableMod(deadlockPath, onDisk.id));
        } else {
            recovered.push(onDisk);
        }
    }

    await fs.unlink(target.path);
    removeModMetadata(target.fileName);

    return {
        recovered,
        missingSourceFileNames,
        shareCode: manifest.shareCode,
    };
}
